# Generated by Django 5.2.17 on 2026-09-09 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la vidéo')),
                ('provider', models.CharField(choices=[('VIMEO', 'Vimeo'), ('CLOUDFLARE', 'Cloudflare Stream'), ('YOUTUBE', 'YouTube'), ('BUNNY', 'Bunny CDN'), ('S3_HLS', 'AWS S3 / HLS (.m3u8)'), ('OTHER', 'Autre / URL direct')], default='YOUTUBE', max_length=20, verbose_name="Fournisseur d'hébergement")),
                ('video_url', models.URLField(help_text='URL principale de lecture ou manifest .m3u8', max_length=500, verbose_name='URL de la vidéo / Flux HLS')),
                ('external_id', models.CharField(blank=True, help_text='ID de la vidéo chez le fournisseur (ex: Cloudflare UID ou Vimeo ID)', max_length=255, null=True, verbose_name='ID Externe / Cloudflare UID')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de la miniature (Thumbnail)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='lessons.lesson', verbose_name='Leçon associée')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
            },
        ),
    ]
