# Generated by Django 5.2.17 on 2026-09-01 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix payé (figé)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Élément de commande',
                'verbose_name_plural': 'Éléments de commande',
            },
        ),
    ]
