# Generated by Django 5.2.16 on 2026-09-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='display order')),
                ('content', models.CharField(max_length=500, verbose_name='requirement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course requirement',
                'verbose_name_plural': 'course requirements',
                'ordering': ['order'],
            },
        ),
    ]
