services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.sso-jwt-secret:/run/secrets/sso_jwt_secret:ro
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py seed_course_type &&
             python manage.py seed_categories &&
             python manage.py seed_courses &&
             python manage.py seed_admin &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=ssodb
      - DB_USER=ssouser
      - DB_PASS=ssopassword
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    env_file:
      - .env.local
    # 🟢 Permet au conteneur de joindre votre machine (et donc le SSO sur le port 8000)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ssodb
      - POSTGRES_USER=ssouser
      - POSTGRES_PASSWORD=ssopassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ssouser -d ssodb"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  dev-db-data:
