# Generated by Django 5.2.17 on 2026-09-03 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la leçon')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description / Résumé de la leçon')),
                ('lesson_type', models.CharField(choices=[('VIDEO', 'Vidéo'), ('ARTICLE', 'Article / Texte'), ('DOCUMENT', 'Document (PDF, PPT...)'), ('QUIZ', 'Quiz / Évaluation')], default='VIDEO', max_length=15, verbose_name='Type de la leçon')),
                ('duration_in_minutes', models.PositiveIntegerField(default=0, verbose_name='Durée estimée (minutes)')),
                ('order', models.PositiveIntegerField(default=1, help_text='Position de la leçon dans le module (1, 2, 3...)', verbose_name="Ordre d'affichage")),
                ('is_preview', models.BooleanField(default=False, help_text='Permet de rendre cette leçon visionnable sans inscription', verbose_name='Aperçu gratuit')),
                ('is_published', models.BooleanField(default=True, help_text='Masque la leçon aux étudiants si décoché', verbose_name='Est publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='modules.module', verbose_name='Module parent')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('module', 'order'), name='unique_lesson_order_per_module')],
            },
        ),
    ]
