# Generated by Django 5.2.16 on 2026-09-08 11:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lab_id', models.UUIDField(help_text='UUID of the Lab in the DRL backend')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Override title (optional)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Position within the lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_activities', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lab Activity',
                'verbose_name_plural': 'Lab Activities',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'order'), name='unique_lab_activity_order_per_lesson')],
            },
        ),
    ]
