# Generated by Django 5.2.16 on 2026-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='quiz type name')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, verbose_name='quiz type description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_question_types', models.ManyToManyField(blank=True, related_name='quiz_types', to='question_types.typequestion', verbose_name='allowed question types')),
            ],
            options={
                'verbose_name': 'quiz type',
                'verbose_name_plural': 'quiz types',
                'ordering': ['name'],
            },
        ),
    ]
