# Generated by Django 5.2.17 on 2026-08-28 10:19

import django.db.models.deletion
import resources.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('lessons', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du fichier / ressource')),
                ('description', models.TextField(blank=True, verbose_name='Description courte')),
                ('resource_type', models.CharField(choices=[('DOCUMENT', 'Document (PDF, Word, TXT)'), ('ARCHIVE', 'Archive (ZIP, RAR, TAR)'), ('CODE', 'Fichier Code / projet (JS, PY, JSON...)'), ('AUDIO', 'Fichier Audio (MP3, WAV)'), ('IMAGE', 'Image / Schéma (PNG, JPG, SVG)'), ('EXTERNAL_LINK', 'Lien externe (GitHub, Notion, Figma)')], default='DOCUMENT', max_length=20, verbose_name='Type de ressource')),
                ('file', models.FileField(blank=True, null=True, upload_to=resources.models.resource_upload_path, verbose_name='Fichier téléchargeable')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien externe (ex: GitHub, Figma)')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='Taille du fichier (en octets)')),
                ('is_preview_allowed', models.BooleanField(default=False, verbose_name='Accessible en aperçu gratuit')),
                ('is_published', models.BooleanField(default=True, verbose_name='Est publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.course', verbose_name='Cours associé')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='lessons.lesson', verbose_name='Leçon associée')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='modules.module', verbose_name='Module associé')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-created_at'],
            },
        ),
    ]
