# Generated by Django 5.2.17 on 2026-09-03 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('description', models.TextField(help_text="Ex: 'Construire une API REST sécurisée avec Django REST Framework'", verbose_name="Description de l'objectif")),
                ('category', models.CharField(choices=[('SKILL', 'Compétence pratique'), ('KNOWLEDGE', 'Connaissance théorique'), ('TOOL', "Maitrise d'outil / logiciel"), ('CERTIFICATION', 'Préparation certification'), ('OTHER', 'Autre')], default='SKILL', max_length=20, verbose_name="Catégorie d'apprentissage")),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône à afficher côté Frontend (ex: 'check-circle', 'code', 'database')", max_length=100, null=True, verbose_name='Icône FontAwesome / Lucide')),
                ('order', models.PositiveIntegerField(default=1, help_text='Position dans la liste des objectifs du cours (1, 2, 3...)', verbose_name="Ordre d'affichage")),
                ('is_highlighted', models.BooleanField(default=False, help_text='Afficher cet objectif en priorité ou sous forme de badge principal', verbose_name='Mettre en avant')),
                ('is_published', models.BooleanField(default=True, help_text='Permet de masquer temporairement un objectif', verbose_name='Est visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course', verbose_name='Cours associé')),
            ],
            options={
                'verbose_name': 'Objectif du cours',
                'verbose_name_plural': 'Objectifs du cours',
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_outcome_order_per_course')],
            },
        ),
    ]
