# Generated by Django 5.2.17 on 2026-09-02 15:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('user_id', models.CharField(blank=True, help_text="ID SSO de l'administrateur ayant créé ce prestataire", max_length=255, null=True, verbose_name='Created By User ID')),
                ('name', models.CharField(help_text='Nom affiché au client (ex: Qavaa, Ignite)', max_length=50, verbose_name='Provider Name')),
                ('code', models.CharField(help_text='Identifiant technique unique du prestataire (ex: QAVAA, IGNITE)', max_length=30, unique=True, verbose_name='Provider Code')),
                ('is_active', models.BooleanField(default=True, help_text='Active ou désactive ce moyen de paiement sur la plateforme', verbose_name='Is Active')),
                ('logo', models.ImageField(blank=True, help_text='Icône ou logo à afficher sur le checkout frontend', null=True, upload_to='payment_providers/', verbose_name='Logo')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Clés API ou paramètres spécifiques', verbose_name='Provider Configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers',
                'ordering': ['name'],
            },
        ),
    ]
