# Generated by Django 5.2.16 on 2026-09-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('skill', 'Skill Path'), ('career', 'Career Path')], max_length=20, verbose_name='path kind')),
                ('title', models.CharField(max_length=255, verbose_name='path title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='path description')),
                ('icon', models.CharField(blank=True, choices=[('git', 'Git'), ('api', 'API'), ('sql', 'SQL'), ('cli', 'Command line'), ('docker', 'Docker'), ('data-viz', 'Data visualization'), ('testing', 'Testing'), ('security', 'Security'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('data', 'Data'), ('cloud', 'Cloud'), ('mobile', 'Mobile')], default='', max_length=20, verbose_name='icon')),
                ('duration_weeks', models.PositiveIntegerField(default=0, verbose_name='duration in weeks')),
                ('pace', models.CharField(blank=True, default='self-paced', max_length=50, verbose_name='pace')),
                ('includes_certificate', models.BooleanField(default=False, verbose_name='Includes certificate')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='learning_paths', to='courses.course', verbose_name='courses')),
            ],
            options={
                'verbose_name': 'learning path',
                'verbose_name_plural': 'learning paths',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PathOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='display order')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='learning_paths.learningpath', verbose_name='learning path')),
            ],
            options={
                'verbose_name': 'path outcome',
                'verbose_name_plural': 'path outcomes',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PathPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='display order')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='learning_paths.learningpath', verbose_name='learning path')),
            ],
            options={
                'verbose_name': 'path prerequisite',
                'verbose_name_plural': 'path prerequisites',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
