# Generated by Django 5.2.16 on 2026-08-03 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLearningPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('title', models.CharField(help_text="Ex: 'Architecture MVC et séparation des responsabilités'", max_length=255, verbose_name="Titre du point d'apprentissage")),
                ('description', models.TextField(blank=True, help_text='Explication plus détaillée de ce que couvre ce point.', verbose_name='Description détaillée')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône UI (ex: 'lightbulb', 'book-open', 'cpu', 'layers')", max_length=100, null=True, verbose_name='Icône FontAwesome / Lucide')),
                ('order', models.PositiveIntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Est visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_points', to='courses.course', verbose_name='Cours associé')),
            ],
            options={
                'verbose_name': "Point d'apprentissage du cours",
                'verbose_name_plural': "Points d'apprentissage du cours",
                'ordering': ['order', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_learning_point_order_per_course')],
            },
        ),
    ]
