# Generated by Django 5.2.17 on 2026-08-28 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('payment_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='Payment Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('currency', models.CharField(default='XOF', help_text='Code devise ISO 4217 (ex: XOF, EUR, USD)', max_length=3, verbose_name='Currency Code')),
                ('transaction_reference', models.CharField(blank=True, help_text='Référence unique de transaction générée par le prestataire (ex: Stripe PaymentIntent ID)', max_length=255, null=True, unique=True, verbose_name='Provider Transaction Reference')),
                ('client_secret', models.CharField(blank=True, help_text='Token ou URL de redirection transmis au Frontend/Mobile pour finaliser le paiement', max_length=255, null=True, verbose_name='Client Secret / Redirect URL')),
                ('raw_response', models.JSONField(blank=True, help_text='Payload JSON complet retourné par le Webhook du prestataire pour audit', null=True, verbose_name='Raw Provider Response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('order', models.ForeignKey(help_text='Commande liée à cette tentative de paiement', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='Associated Order')),
                ('provider', models.ForeignKey(help_text='Prestataire utilisé pour exécuter la transaction', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payment_providers.paymentprovider', verbose_name='Payment Provider')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
