# Generated by Django 5.2.17 on 2026-09-03 12:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('code', models.CharField(help_text='Ex: WELCOME2026 ou PYTHON50', max_length=50, unique=True, verbose_name='Code promo')),
                ('discount_percentage', models.PositiveIntegerField(help_text='Valeur comprise entre 1 et 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Pourcentage de réduction (%)')),
                ('active', models.BooleanField(default=True, help_text='Permet de désactiver manuellement le code promo.', verbose_name='Actif')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir du')),
                ('valid_to', models.DateTimeField(verbose_name="Valide jusqu'au")),
                ('max_uses', models.PositiveIntegerField(default=0, help_text="Mettez 0 pour un nombre illimité d'utilisations.", verbose_name='Utilisations maximales')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name="Nombre d'utilisations effectuées")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('course', models.ForeignKey(blank=True, help_text="Laissez vide si le coupon s'applique globalement à tout le panier.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='courses.course', verbose_name='Cours spécifique')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
