# Generated by Django 5.2.17 on 2026-09-03 12:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='ID Utilisateur (sub)')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email Utilisateur')),
                ('user_roles', models.JSONField(default=list, verbose_name='Rôles Utilisateur')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('english', 'English'), ('french', 'French')], default='english', max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all', 'All')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('thumbnail', models.CharField(blank=True, help_text='Local path (e.g., /media/courses/img.png) or external URL (e.g., https://site.com/img.png)', max_length=500, null=True)),
                ('promo_video_url', models.CharField(blank=True, help_text='External URL (YouTube, Vimeo, Cloudinary) or local path to video.', max_length=500, null=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='courses', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
    ]
