# Generated by Django 5.2.16 on 2026-09-01 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(verbose_name='SSO user id')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20, verbose_name='status')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='progress percent')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course progress',
                'verbose_name_plural': 'course progress',
                'ordering': ['-updated_at'],
                'unique_together': {('user_id', 'course')},
            },
        ),
    ]
