# Generated by Django 5.2.17 on 2026-09-03 12:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID Identifier')),
                ('user_id', models.CharField(db_index=True, max_length=255, verbose_name='ID Utilisateur (sub)')),
                ('user_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name="Email de l'utilisateur")),
                ('user_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rôle principal')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Amount')),
                ('discount_code_snapshot', models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount Code Snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Order Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='discounts.discount', verbose_name='Applied Discount')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='orders_orde_user_id_02a211_idx')],
            },
        ),
    ]
