# Generated by Django 5.2.16 on 2026-09-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_types', '0001_initial'),
        ('quiz_questions', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='question_types.typequestion', verbose_name='question type'),
        ),
    ]
