# Generated by Django 5.2.16 on 2026-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('is_completed', models.BooleanField(default=False, verbose_name='completed')),
            ],
            options={
                'verbose_name': 'quiz attempt',
                'verbose_name_plural': 'quiz attempts',
                'ordering': ['-started_at'],
            },
        ),
    ]
