--
-- PostgreSQL database dump
--

\restrict W2OoopVba6Nd70qph6LJOj5zz2DltELpusW20MQLtK22Y9cHZyUlg9CLJRXwPI2

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_course; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_course (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    subtitle character varying(255),
    description text,
    language character varying(10) NOT NULL,
    level character varying(20) NOT NULL,
    slug character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    thumbnail character varying(200),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    type_id bigint,
    duration_minutes integer NOT NULL,
    instructor character varying(255) NOT NULL,
    rating double precision,
    review_count integer NOT NULL,
    audience text NOT NULL,
    cohort_label character varying(120) NOT NULL,
    downloadable_files_count integer NOT NULL,
    original_price numeric(8,2),
    price numeric(8,2) NOT NULL,
    CONSTRAINT courses_course_downloadable_files_count_check CHECK ((downloadable_files_count >= 0)),
    CONSTRAINT courses_course_duration_minutes_check CHECK ((duration_minutes >= 0)),
    CONSTRAINT courses_course_review_count_check CHECK ((review_count >= 0))
);


--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_type_typecourse; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses_type_typecourse (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    description character varying NOT NULL,
    is_virtual boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: courses_type_typecourse_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.courses_type_typecourse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_type_typecourse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: highlights_coursehighlight; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.highlights_coursehighlight (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    content character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT highlights_coursehighlight_order_check CHECK (("order" >= 0))
);


--
-- Name: highlights_coursehighlight_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.highlights_coursehighlight ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.highlights_coursehighlight_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_paths_learningpath; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_paths_learningpath (
    id bigint NOT NULL,
    kind character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    description text,
    icon character varying(20) NOT NULL,
    duration_weeks integer NOT NULL,
    "order" integer NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    includes_certificate boolean NOT NULL,
    pace character varying(50) NOT NULL,
    CONSTRAINT learning_paths_learningpath_duration_weeks_check CHECK ((duration_weeks >= 0)),
    CONSTRAINT learning_paths_learningpath_order_check CHECK (("order" >= 0))
);


--
-- Name: learning_paths_learningpath_courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_paths_learningpath_courses (
    id bigint NOT NULL,
    learningpath_id bigint NOT NULL,
    course_id bigint NOT NULL
);


--
-- Name: learning_paths_learningpath_courses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_paths_learningpath_courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_paths_learningpath_courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_paths_learningpath_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_paths_learningpath ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_paths_learningpath_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_paths_pathoutcome; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_paths_pathoutcome (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    path_id bigint NOT NULL,
    CONSTRAINT learning_paths_pathoutcome_order_check CHECK (("order" >= 0))
);


--
-- Name: learning_paths_pathoutcome_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_paths_pathoutcome ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_paths_pathoutcome_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_paths_pathprerequisite; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_paths_pathprerequisite (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    path_id bigint NOT NULL,
    CONSTRAINT learning_paths_pathprerequisite_order_check CHECK (("order" >= 0))
);


--
-- Name: learning_paths_pathprerequisite_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_paths_pathprerequisite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_paths_pathprerequisite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_points_courselearningpoint; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_points_courselearningpoint (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    content character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT learning_points_courselearningpoint_order_check CHECK (("order" >= 0))
);


--
-- Name: learning_points_courselearningpoint_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_points_courselearningpoint ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_points_courselearningpoint_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lessons_lesson; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lessons_lesson (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    slug character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    module_id bigint NOT NULL,
    duration_minutes integer NOT NULL,
    lesson_type character varying(10) NOT NULL,
    CONSTRAINT lessons_lesson_duration_minutes_check CHECK ((duration_minutes >= 0)),
    CONSTRAINT lessons_lesson_order_check CHECK (("order" >= 0))
);


--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lessons_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lessons_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: modules_module; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.modules_module (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    "order" integer NOT NULL,
    slug character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT modules_module_order_check CHECK (("order" >= 0))
);


--
-- Name: modules_module_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.modules_module ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.modules_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: outcomes_courseoutcome; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.outcomes_courseoutcome (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    content character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT outcomes_courseoutcome_order_check CHECK (("order" >= 0))
);


--
-- Name: outcomes_courseoutcome_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.outcomes_courseoutcome ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outcomes_courseoutcome_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: progress_courseprogress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.progress_courseprogress (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    status character varying(20) NOT NULL,
    progress_percent integer NOT NULL,
    completed_at timestamp with time zone,
    course_id bigint NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT progress_courseprogress_progress_percent_check CHECK ((progress_percent >= 0))
);


--
-- Name: question_types_typequestion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.question_types_typequestion (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    description character varying NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: question_types_typequestion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.question_types_typequestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_types_typequestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_answers_quizanswer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_answers_quizanswer (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    attempt_id bigint NOT NULL,
    option_id bigint NOT NULL,
    question_id bigint NOT NULL
);


--
-- Name: quiz_answers_quizanswer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_answers_quizanswer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_answers_quizanswer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_attempts_quizattempt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_attempts_quizattempt (
    id bigint NOT NULL,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    is_completed boolean NOT NULL,
    quiz_id bigint NOT NULL
);


--
-- Name: quiz_attempts_quizattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_attempts_quizattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_attempts_quizattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_options_quizoption; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_options_quizoption (
    id bigint NOT NULL,
    text character varying(500) NOT NULL,
    is_correct boolean NOT NULL,
    "order" integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    question_id bigint NOT NULL,
    CONSTRAINT quiz_options_quizoption_order_check CHECK (("order" >= 0))
);


--
-- Name: quiz_options_quizoption_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_options_quizoption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_options_quizoption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_questions_question; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_questions_question (
    id bigint NOT NULL,
    text text NOT NULL,
    "order" integer NOT NULL,
    slug character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    quiz_id bigint NOT NULL,
    type_question_id bigint,
    CONSTRAINT quiz_questions_question_order_check CHECK (("order" >= 0))
);


--
-- Name: quiz_questions_question_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_questions_question ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_questions_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_results_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_results_result (
    id bigint NOT NULL,
    is_correct boolean NOT NULL,
    score numeric(5,2),
    feedback text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    answer_id bigint NOT NULL
);


--
-- Name: quiz_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_results_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_types_typequiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_types_typequiz (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    description character varying NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: quiz_types_typequiz_allowed_question_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quiz_types_typequiz_allowed_question_types (
    id bigint NOT NULL,
    typequiz_id bigint NOT NULL,
    typequestion_id bigint NOT NULL
);


--
-- Name: quiz_types_typequiz_allowed_question_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_types_typequiz_allowed_question_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_types_typequiz_allowed_question_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quiz_types_typequiz_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quiz_types_typequiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quiz_types_typequiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: quizzes_quiz; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.quizzes_quiz (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    object_id integer,
    slug character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    content_type_id integer,
    type_quiz_id bigint,
    CONSTRAINT quizzes_quiz_object_id_check CHECK ((object_id >= 0))
);


--
-- Name: quizzes_quiz_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.quizzes_quiz ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quizzes_quiz_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requirements_courserequirement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requirements_courserequirement (
    id bigint NOT NULL,
    "order" integer NOT NULL,
    content character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT requirements_courserequirement_order_check CHECK (("order" >= 0))
);


--
-- Name: requirements_courserequirement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requirements_courserequirement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requirements_courserequirement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: videos_video; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.videos_video (
    id bigint NOT NULL,
    url character varying(200) NOT NULL,
    duration_seconds integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    lesson_id bigint NOT NULL,
    CONSTRAINT videos_video_duration_seconds_check CHECK ((duration_seconds >= 0))
);


--
-- Name: videos_video_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.videos_video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.videos_video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add course type	7	add_typecourse
26	Can change course type	7	change_typecourse
27	Can delete course type	7	delete_typecourse
28	Can view course type	7	view_typecourse
29	Can add course	8	add_course
30	Can change course	8	change_course
31	Can delete course	8	delete_course
32	Can view course	8	view_course
33	Can add course highlight	9	add_coursehighlight
34	Can change course highlight	9	change_coursehighlight
35	Can delete course highlight	9	delete_coursehighlight
36	Can view course highlight	9	view_coursehighlight
37	Can add course outcome	10	add_courseoutcome
38	Can change course outcome	10	change_courseoutcome
39	Can delete course outcome	10	delete_courseoutcome
40	Can view course outcome	10	view_courseoutcome
41	Can add course learning point	11	add_courselearningpoint
42	Can change course learning point	11	change_courselearningpoint
43	Can delete course learning point	11	delete_courselearningpoint
44	Can view course learning point	11	view_courselearningpoint
45	Can add course requirement	12	add_courserequirement
46	Can change course requirement	12	change_courserequirement
47	Can delete course requirement	12	delete_courserequirement
48	Can view course requirement	12	view_courserequirement
49	Can add module	13	add_module
50	Can change module	13	change_module
51	Can delete module	13	delete_module
52	Can view module	13	view_module
53	Can add lesson	14	add_lesson
54	Can change lesson	14	change_lesson
55	Can delete lesson	14	delete_lesson
56	Can view lesson	14	view_lesson
57	Can add video	15	add_video
58	Can change video	15	change_video
59	Can delete video	15	delete_video
60	Can view video	15	view_video
61	Can add quiz type	16	add_typequiz
62	Can change quiz type	16	change_typequiz
63	Can delete quiz type	16	delete_typequiz
64	Can view quiz type	16	view_typequiz
65	Can add question type	17	add_typequestion
66	Can change question type	17	change_typequestion
67	Can delete question type	17	delete_typequestion
68	Can view question type	17	view_typequestion
69	Can add quiz	18	add_quiz
70	Can change quiz	18	change_quiz
71	Can delete quiz	18	delete_quiz
72	Can view quiz	18	view_quiz
73	Can add quiz question	19	add_question
74	Can change quiz question	19	change_question
75	Can delete quiz question	19	delete_question
76	Can view quiz question	19	view_question
77	Can add quiz option	20	add_quizoption
78	Can change quiz option	20	change_quizoption
79	Can delete quiz option	20	delete_quizoption
80	Can view quiz option	20	view_quizoption
81	Can add quiz attempt	21	add_quizattempt
82	Can change quiz attempt	21	change_quizattempt
83	Can delete quiz attempt	21	delete_quizattempt
84	Can view quiz attempt	21	view_quizattempt
85	Can add quiz answer	22	add_quizanswer
86	Can change quiz answer	22	change_quizanswer
87	Can delete quiz answer	22	delete_quizanswer
88	Can view quiz answer	22	view_quizanswer
89	Can add quiz result	23	add_result
90	Can change quiz result	23	change_result
91	Can delete quiz result	23	delete_result
92	Can view quiz result	23	view_result
93	Can add learning path	24	add_learningpath
94	Can change learning path	24	change_learningpath
95	Can delete learning path	24	delete_learningpath
96	Can view learning path	24	view_learningpath
97	Can add path outcome	25	add_pathoutcome
98	Can change path outcome	25	change_pathoutcome
99	Can delete path outcome	25	delete_pathoutcome
100	Can view path outcome	25	view_pathoutcome
101	Can add path prerequisite	26	add_pathprerequisite
102	Can change path prerequisite	26	change_pathprerequisite
103	Can delete path prerequisite	26	delete_pathprerequisite
104	Can view path prerequisite	26	view_pathprerequisite
105	Can add course progress	27	add_courseprogress
106	Can change course progress	27	change_courseprogress
107	Can delete course progress	27	delete_courseprogress
108	Can view course progress	27	view_courseprogress
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$O38HpMmsvNs7Eg8gI85QtG$MtHBvmTiZo6rFMCDOv6UvnSWqNuepH+vyk38HaHcZ2U=	2026-08-28 09:20:17.680764+00	t	chimaobi			wisdomchimaobi7@gmail.com	t	t	2026-08-21 12:57:21.161376+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: courses_course; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_course (id, title, subtitle, description, language, level, slug, is_active, thumbnail, created_at, updated_at, type_id, duration_minutes, instructor, rating, review_count, audience, cohort_label, downloadable_files_count, original_price, price) FROM stdin;
1	python	Data Structure	xyz	en	beginner	python	t		2026-07-21 17:15:30.276458+00	2026-07-21 17:15:30.276698+00	1	0		\N	0			0	\N	0.00
2	Learn Javascript	Data Structure	vgyjfkhkhliikgu	en	beginner	learn-javascript	t	\N	2026-08-21 13:13:03.376601+00	2026-08-21 13:13:03.376639+00	1	0		\N	0			0	\N	0.00
7	Deployment & Production Operations	Docker, CI/CD, monitoring and safe releases	Ship services to production with Docker and CI/CD, then keep them observable.	en	advanced	deployment-production-operations	t	\N	2026-08-21 17:30:44.857034+00	2026-08-27 20:13:43.255808+00	1	735	Lena Hoffmann	4.9	389	Engineers whose code now runs somewhere real and who need containers, pipelines, alerts and rollback plans instead of Friday deploys.	Limited cohort	18	89.00	56.00
3	Foundations of Server-Side Programming	How servers, requests and responses really work	Build the mental model behind every backend: processes, sockets, HTTP semantics and clean server-side architecture.	en	beginner	foundations-of-server-side-programming	t	\N	2026-08-21 17:30:44.813353+00	2026-08-27 20:13:43.208789+00	1	380	Reza Ahmadi	4.8	1204	Developers who have shipped small scripts or frontend apps and want a solid mental model of how servers handle requests before touching a framework.	Limited cohort	12	65.00	39.00
4	Designing RESTful APIs	Resources, verbs and versioning done right	Design predictable, well-versioned REST APIs that clients enjoy consuming.	en	intermediate	designing-restful-apis	t	\N	2026-08-21 17:30:44.826634+00	2026-08-27 20:13:43.227549+00	1	585	Nadia Kovacs	4.9	987	Backend developers who can build endpoints but want their APIs to stay predictable as teams, clients and traffic grow.	Limited cohort	18	76.00	48.00
5	Relational Databases & SQL Mastery	Schema design, joins, indexes and query plans	Model relational schemas and write optimized SQL for real application workloads.	en	intermediate	relational-databases-sql-mastery	t	\N	2026-08-21 17:30:44.834229+00	2026-08-27 20:13:43.237066+00	1	670	Takashi Mori	4.7	762	Application developers who write SQL by hand but cannot yet read a query plan or defend a schema under review.	Limited cohort	15	84.00	52.00
6	Authentication, Security & Middleware	JWT, OAuth 2.0 and hardened request pipelines	Implement secure authentication flows and middleware pipelines for real traffic.	en	intermediate	authentication-security-middleware	t	\N	2026-08-21 17:30:44.846446+00	2026-08-27 20:13:43.246723+00	1	510	Amara Diallo	4.8	541	Developers building multi-user products who must move from 'it logs in' to tokens, scopes and request pipelines that survive an audit.	Limited cohort	10	72.00	45.00
\.


--
-- Data for Name: courses_type_typecourse; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.courses_type_typecourse (id, name, slug, description, is_virtual, is_active, created_at, updated_at) FROM stdin;
1	E-learning	e-learning	Online courses with pre-recorded videos and quizzes.	t	t	2026-07-17 20:05:22.262048+00	2026-07-17 20:05:22.262069+00
2	Live Classroom	live-classroom	Interactive online courses via live video streaming.	t	t	2026-07-17 20:05:22.271322+00	2026-07-17 20:05:22.27134+00
3	In-Person Workshop	in-person-workshop	Face-to-face practical courses in a physical classroom.	f	t	2026-07-17 20:05:22.281795+00	2026-07-17 20:05:22.282236+00
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-08-21 13:13:03.425186+00	2	Learn Javascript	1	[{"added": {}}]	8	1
2	2026-08-21 16:04:15.906458+00	1	Skill Path: Git & Version Control	2	[{"changed": {"fields": ["Courses"]}}]	24	1
3	2026-08-21 22:40:45.480949+00	1	Skill Path: Git & Version Control	2	[{"changed": {"fields": ["Courses"]}}, {"added": {"name": "path outcome", "object": "Design and build production-ready REST APIs"}}, {"added": {"name": "path outcome", "object": "Model relational schemas and write optimized SQL"}}, {"added": {"name": "path prerequisite", "object": "Comfort with any programming language"}}]	24	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	courses_type	typecourse
8	courses	course
9	highlights	coursehighlight
10	outcomes	courseoutcome
11	learning_points	courselearningpoint
12	requirements	courserequirement
13	modules	module
14	lessons	lesson
15	videos	video
16	quiz_types	typequiz
17	question_types	typequestion
18	quizzes	quiz
19	quiz_questions	question
20	quiz_options	quizoption
21	quiz_attempts	quizattempt
22	quiz_answers	quizanswer
23	quiz_results	result
24	learning_paths	learningpath
25	learning_paths	pathoutcome
26	learning_paths	pathprerequisite
27	progress	courseprogress
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-07-17 20:05:16.459102+00
2	auth	0001_initial	2026-07-17 20:05:16.690834+00
3	admin	0001_initial	2026-07-17 20:05:16.751345+00
4	admin	0002_logentry_remove_auto_add	2026-07-17 20:05:16.769444+00
5	admin	0003_logentry_add_action_flag_choices	2026-07-17 20:05:16.785439+00
6	contenttypes	0002_remove_content_type_name	2026-07-17 20:05:16.826054+00
7	auth	0002_alter_permission_name_max_length	2026-07-17 20:05:16.8494+00
8	auth	0003_alter_user_email_max_length	2026-07-17 20:05:16.864676+00
9	auth	0004_alter_user_username_opts	2026-07-17 20:05:16.897714+00
10	auth	0005_alter_user_last_login_null	2026-07-17 20:05:16.921638+00
11	auth	0006_require_contenttypes_0002	2026-07-17 20:05:16.926163+00
12	auth	0007_alter_validators_add_error_messages	2026-07-17 20:05:16.9591+00
13	auth	0008_alter_user_username_max_length	2026-07-17 20:05:17.00562+00
14	auth	0009_alter_user_last_name_max_length	2026-07-17 20:05:17.02043+00
15	auth	0010_alter_group_name_max_length	2026-07-17 20:05:17.080528+00
16	auth	0011_update_proxy_permissions	2026-07-17 20:05:17.118808+00
17	auth	0012_alter_user_first_name_max_length	2026-07-17 20:05:17.157471+00
18	courses_type	0001_initial	2026-07-17 20:05:17.281811+00
19	courses	0001_initial	2026-07-17 20:05:17.348165+00
20	highlights	0001_initial	2026-07-17 20:05:17.395815+00
21	learning_points	0001_initial	2026-07-17 20:05:17.429723+00
22	modules	0001_initial	2026-07-17 20:05:17.490292+00
23	lessons	0001_initial	2026-07-17 20:05:17.547478+00
24	lessons	0002_initial	2026-07-17 20:05:17.600143+00
25	outcomes	0001_initial	2026-07-17 20:05:17.655888+00
26	question_types	0001_initial	2026-07-17 20:05:17.719982+00
27	quiz_questions	0001_initial	2026-07-17 20:05:17.768806+00
28	quiz_options	0001_initial	2026-07-17 20:05:17.806497+00
29	quiz_attempts	0001_initial	2026-07-17 20:05:17.83133+00
30	quiz_answers	0001_initial	2026-07-17 20:05:17.850082+00
31	quiz_answers	0002_initial	2026-07-17 20:05:17.895692+00
32	quiz_answers	0003_initial	2026-07-17 20:05:17.933446+00
33	quiz_answers	0004_initial	2026-07-17 20:05:18.00351+00
34	quiz_types	0001_initial	2026-07-17 20:05:18.113121+00
35	quizzes	0001_initial	2026-07-17 20:05:18.180978+00
36	quiz_attempts	0002_initial	2026-07-17 20:05:18.213973+00
37	quiz_options	0002_initial	2026-07-17 20:05:18.259296+00
38	quiz_questions	0002_initial	2026-07-17 20:05:18.34426+00
39	quiz_results	0001_initial	2026-07-17 20:05:18.415617+00
40	requirements	0001_initial	2026-07-17 20:05:18.476278+00
41	sessions	0001_initial	2026-07-17 20:05:18.523412+00
42	videos	0001_initial	2026-07-17 20:05:18.590595+00
43	learning_paths	0001_initial	2026-08-21 15:51:37.929805+00
44	courses	0002_course_duration_minutes_course_instructor_and_more	2026-08-21 17:30:36.057531+00
45	learning_paths	0002_learningpath_includes_certificate_learningpath_pace_and_more	2026-08-21 17:30:36.315723+00
46	progress	0001_initial	2026-08-21 17:30:36.43252+00
47	learning_paths	0003_alter_pathoutcome_path_alter_pathprerequisite_path	2026-08-21 17:46:48.240973+00
48	progress	0002_alter_courseprogress_options_and_more	2026-08-21 19:09:57.26831+00
49	courses	0003_course_audience_course_cohort_label_and_more	2026-08-22 11:47:20.541898+00
50	lessons	0003_lesson_duration_minutes_lesson_lesson_type	2026-08-22 11:47:20.599783+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
9dh4ejz2jaizh4blt6ier5q8sc61agvc	.eJxVjMEOwiAQRP-FsyFsF1rr0Xu_odllQaoGktKejP-uJD3oZQ7z3sxLzbRvad5rWOdF1EWBOv12TP4RcgNyp3wr2pe8rQvrpuiDVj0VCc_r4f4dJKqprc8YohssUodBoGcRoQAIZIz1BsH7EYVHZ_voQNACD_wNZvHRmE69P_Y3OGI:1wxOod:ym4X-RlI2CeBuwl9nbFZVu4NfkluqYVRnsNCxiwX6lM	2026-09-04 12:57:47.361379+00
dzwut33vemsqjepamxd7wpz1js84n08v	.eJxVjMEOwiAQRP-FsyFsF1rr0Xu_odllQaoGktKejP-uJD3oZQ7z3sxLzbRvad5rWOdF1EWBOv12TP4RcgNyp3wr2pe8rQvrpuiDVj0VCc_r4f4dJKqprc8YohssUodBoGcRoQAIZIz1BsH7EYVHZ_voQNACD_wNZvHRmE69P_Y3OGI:1wxn1c:XeDbKx7utMCEstFH0Z4qhRe0W5OjEC7Q5DTOa2UYaa4	2026-09-05 14:48:48.113679+00
b5zscs36svt11go7rqfcxvt05mdd17pr	.eJxVjMEOwiAQRP-FsyFsF1rr0Xu_odllQaoGktKejP-uJD3oZQ7z3sxLzbRvad5rWOdF1EWBOv12TP4RcgNyp3wr2pe8rQvrpuiDVj0VCc_r4f4dJKqprc8YohssUodBoGcRoQAIZIz1BsH7EYVHZ_voQNACD_wNZvHRmE69P_Y3OGI:1wzskz:pm3y2nUgsFCyvR-0xyTfWC386yPt8Ef8JkXOdSofsdU	2026-09-11 09:20:17.696702+00
\.


--
-- Data for Name: highlights_coursehighlight; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.highlights_coursehighlight (id, "order", content, created_at, course_id) FROM stdin;
\.


--
-- Data for Name: learning_paths_learningpath; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.learning_paths_learningpath (id, kind, title, slug, description, icon, duration_weeks, "order", is_active, created_at, updated_at, includes_certificate, pace) FROM stdin;
2	skill	API Design Basics	api-design-basics	Design clean, consistent REST endpoints	api	4	2	t	2026-08-21 15:51:46.756156+00	2026-08-21 15:51:46.756182+00	f	self-paced
3	skill	SQL Fundamentals	sql-fundamentals	Query, join, and shape relational data confidently	sql	5	3	t	2026-08-21 15:51:46.770326+00	2026-08-21 15:51:46.770357+00	f	self-paced
4	skill	Command Line Essentials	command-line-essentials	Navigate and automate from the terminal	cli	2	4	t	2026-08-21 15:51:46.783294+00	2026-08-21 15:51:46.783321+00	f	self-paced
5	skill	Docker Basics	docker-basics	Containerize and ship applications reliably	docker	4	5	t	2026-08-21 15:51:46.800118+00	2026-08-21 15:51:46.800164+00	f	self-paced
6	skill	Data Visualization	data-visualization	Turn numbers into charts people actually read	data-viz	3	6	t	2026-08-21 15:51:46.814217+00	2026-08-21 15:51:46.814268+00	f	self-paced
7	skill	Testing Fundamentals	testing-fundamentals	Write tests that catch real bugs	testing	4	7	t	2026-08-21 15:51:46.831392+00	2026-08-21 15:51:46.83146+00	f	self-paced
8	skill	Authentication & Security Basics	authentication-security-basics	Implement login flows and protect user data	security	3	8	t	2026-08-21 15:51:46.847603+00	2026-08-21 15:51:46.847682+00	f	self-paced
9	career	Backend Developer	backend-developer	Build and deploy production-ready APIs and services	backend	12	9	t	2026-08-21 15:51:46.857613+00	2026-08-21 15:51:46.857639+00	f	self-paced
10	career	Frontend Developer	frontend-developer	Ship accessible, responsive interfaces users trust	frontend	14	10	t	2026-08-21 15:51:46.873986+00	2026-08-21 15:51:46.87402+00	f	self-paced
11	career	Data Analyst	data-analyst	Turn raw data into decisions leaders act on	data	10	11	t	2026-08-21 15:51:46.889607+00	2026-08-21 15:51:46.889634+00	f	self-paced
12	career	Cloud Engineer	cloud-engineer	Automate infrastructure that scales without drama	cloud	16	12	t	2026-08-21 15:51:46.90554+00	2026-08-21 15:51:46.905609+00	f	self-paced
13	career	Cybersecurity Analyst	cybersecurity-analyst	Detect, investigate and contain real-world threats	security	13	13	t	2026-08-21 15:51:46.916565+00	2026-08-21 15:51:46.916591+00	f	self-paced
14	career	Mobile Developer	mobile-developer	Publish cross-platform apps to both app stores	mobile	9	14	t	2026-08-21 15:51:46.931572+00	2026-08-21 15:51:46.93161+00	f	self-paced
1	skill	Git & Version Control	git-version-control	Master branching, merging, and collaborative workflows	git	3	1	t	2026-08-21 15:51:46.724684+00	2026-08-21 22:40:45.391836+00	f	self-paced
\.


--
-- Data for Name: learning_paths_learningpath_courses; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.learning_paths_learningpath_courses (id, learningpath_id, course_id) FROM stdin;
3	9	3
4	9	4
5	9	5
6	9	6
7	9	7
\.


--
-- Data for Name: learning_paths_pathoutcome; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.learning_paths_pathoutcome (id, "order", content, created_at, path_id) FROM stdin;
1	1	Design and build production-ready REST APIs	2026-08-21 17:35:49.500258+00	9
2	2	Model relational schemas and write optimized SQL	2026-08-21 17:35:49.512843+00	9
3	3	Implement secure authentication flows (JWT, OAuth 2.0)	2026-08-21 17:35:49.524206+00	9
4	4	Deploy backend services using Docker and CI/CD	2026-08-21 17:35:49.534974+00	9
5	5	Monitor, log, and debug live production systems	2026-08-21 17:35:49.54605+00	9
6	6	Manage environment config and secrets safely	2026-08-21 17:35:49.556129+00	9
7	1	Design and build production-ready REST APIs	2026-08-21 22:40:45.45955+00	1
8	2	Model relational schemas and write optimized SQL	2026-08-21 22:40:45.471896+00	1
\.


--
-- Data for Name: learning_paths_pathprerequisite; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.learning_paths_pathprerequisite (id, "order", content, created_at, path_id) FROM stdin;
1	1	Comfort with any programming language	2026-08-21 17:35:49.577262+00	9
2	2	Basic understanding of the web (HTTP, browsers)	2026-08-21 17:35:49.591025+00	9
3	1	Comfort with any programming language	2026-08-21 22:40:45.472746+00	1
\.


--
-- Data for Name: learning_points_courselearningpoint; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.learning_points_courselearningpoint (id, "order", content, created_at, course_id) FROM stdin;
\.


--
-- Data for Name: lessons_lesson; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.lessons_lesson (id, title, description, "order", slug, is_active, created_at, updated_at, module_id, duration_minutes, lesson_type) FROM stdin;
1	What makes an API RESTful		1	rest-api-resource-modeling-01	t	2026-08-22 11:52:30.700264+00	2026-08-27 20:13:43.308773+00	1	12	video
2	Resources, URIs and naming conventions		2	rest-api-resource-modeling-02	t	2026-08-22 11:52:30.717306+00	2026-08-27 20:13:43.315584+00	1	18	video
3	HTTP verbs beyond GET and POST		3	rest-api-resource-modeling-03	t	2026-08-22 11:52:30.726038+00	2026-08-27 20:13:43.320379+00	1	21	video
4	Resource modeling check		4	rest-api-resource-modeling-04	t	2026-08-22 11:52:30.735228+00	2026-08-27 20:13:43.32516+00	1	6	quiz
5	Status codes that mean something		1	rest-api-status-codes-and-errors-01	t	2026-08-22 11:52:30.782941+00	2026-08-27 20:13:43.331654+00	2	16	video
6	Error responses clients can act on		2	rest-api-status-codes-and-errors-02	t	2026-08-22 11:52:30.807004+00	2026-08-27 20:13:43.336592+00	2	19	video
7	Idempotency and safe retries		3	rest-api-status-codes-and-errors-03	t	2026-08-22 11:52:30.824571+00	2026-08-27 20:13:43.341607+00	2	14	video
8	Contracts check		4	rest-api-status-codes-and-errors-04	t	2026-08-22 11:52:30.832633+00	2026-08-27 20:13:43.34621+00	2	8	quiz
9	Why APIs break and how to avoid it		1	rest-api-versioning-and-evolution-01	t	2026-08-22 11:52:30.848322+00	2026-08-27 20:13:43.354379+00	3	17	video
10	URL versioning vs header versioning		2	rest-api-versioning-and-evolution-02	t	2026-08-22 11:52:30.858395+00	2026-08-27 20:13:43.361035+00	3	22	video
11	Deprecation without drama		3	rest-api-versioning-and-evolution-03	t	2026-08-22 11:52:30.871194+00	2026-08-27 20:13:43.367312+00	3	15	video
12	Versioning check		4	rest-api-versioning-and-evolution-04	t	2026-08-22 11:52:30.904858+00	2026-08-27 20:13:43.373856+00	3	7	quiz
13	OpenAPI as a design tool		1	rest-api-documentation-and-consistency-01	t	2026-08-22 11:52:30.922758+00	2026-08-27 20:13:43.38197+00	4	20	video
14	Pagination, filtering and sorting conventions		2	rest-api-documentation-and-consistency-02	t	2026-08-22 11:52:30.929935+00	2026-08-27 20:13:43.388512+00	4	24	video
15	Auditing a real API design		3	rest-api-documentation-and-consistency-03	t	2026-08-22 11:52:30.935732+00	2026-08-27 20:13:43.395055+00	4	27	video
16	Final assessment		4	rest-api-documentation-and-consistency-04	t	2026-08-22 11:52:30.942182+00	2026-08-27 20:13:43.401258+00	4	15	quiz
\.


--
-- Data for Name: modules_module; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.modules_module (id, title, description, "order", slug, is_active, created_at, updated_at, course_id) FROM stdin;
1	Resource Modeling		1	rest-api-resource-modeling	t	2026-08-22 11:52:30.666303+00	2026-08-22 11:52:30.666323+00	4
2	Status Codes & Errors		2	rest-api-status-codes-and-errors	t	2026-08-22 11:52:30.746494+00	2026-08-22 11:52:30.746549+00	4
3	Versioning & Evolution		3	rest-api-versioning-and-evolution	t	2026-08-22 11:52:30.841995+00	2026-08-22 11:52:30.842041+00	4
4	Documentation & Consistency		4	rest-api-documentation-and-consistency	t	2026-08-22 11:52:30.910181+00	2026-08-22 11:52:30.910199+00	4
5	example		1	example	t	2026-08-29 14:56:31.271624+00	2026-08-29 14:56:31.272461+00	6
\.


--
-- Data for Name: outcomes_courseoutcome; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.outcomes_courseoutcome (id, "order", content, created_at, course_id) FROM stdin;
\.


--
-- Data for Name: progress_courseprogress; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.progress_courseprogress (id, user_id, status, progress_percent, completed_at, course_id, updated_at) FROM stdin;
474471d0-1265-4fd5-b05f-72dcde4b6814	3968e9d3-32ef-405e-a398-ff3d812b2420	in_progress	0	\N	7	2026-08-21 19:27:13.635307+00
e47fe003-b1bc-4ea3-8934-e2bba5885c50	3968e9d3-32ef-405e-a398-ff3d812b2420	in_progress	0	\N	4	2026-08-21 19:27:39.01268+00
e27c9e42-72f1-466c-a5d0-d16df46f9d89	3968e9d3-32ef-405e-a398-ff3d812b2420	in_progress	0	\N	3	2026-08-21 19:27:51.469448+00
986353df-4e60-4490-9b7a-5e9e9fa280ad	3968e9d3-32ef-405e-a398-ff3d812b2420	in_progress	0	\N	5	2026-08-21 19:28:02.006507+00
2e65ac4f-ae81-4b47-b3ef-61079b3ffab9	3968e9d3-32ef-405e-a398-ff3d812b2420	in_progress	99	\N	6	2026-08-21 23:46:06.828281+00
3d8ac86a-e065-4de2-8f83-862b3a753736	9d2fcad3-0f3d-4ff1-9195-61ecef7effba	in_progress	0	\N	4	2026-08-22 14:32:59.933959+00
cd72aa0d-7b3b-4931-9d7c-2dbfefb2aef0	9d2fcad3-0f3d-4ff1-9195-61ecef7effba	completed	100	2026-08-22 14:33:00.320584+00	5	2026-08-22 14:33:00.331545+00
\.


--
-- Data for Name: question_types_typequestion; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.question_types_typequestion (id, name, slug, description, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: quiz_answers_quizanswer; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_answers_quizanswer (id, created_at, attempt_id, option_id, question_id) FROM stdin;
\.


--
-- Data for Name: quiz_attempts_quizattempt; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_attempts_quizattempt (id, started_at, completed_at, is_completed, quiz_id) FROM stdin;
\.


--
-- Data for Name: quiz_options_quizoption; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_options_quizoption (id, text, is_correct, "order", created_at, question_id) FROM stdin;
\.


--
-- Data for Name: quiz_questions_question; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_questions_question (id, text, "order", slug, is_active, created_at, updated_at, quiz_id, type_question_id) FROM stdin;
\.


--
-- Data for Name: quiz_results_result; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_results_result (id, is_correct, score, feedback, created_at, answer_id) FROM stdin;
\.


--
-- Data for Name: quiz_types_typequiz; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_types_typequiz (id, name, slug, description, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: quiz_types_typequiz_allowed_question_types; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quiz_types_typequiz_allowed_question_types (id, typequiz_id, typequestion_id) FROM stdin;
\.


--
-- Data for Name: quizzes_quiz; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.quizzes_quiz (id, title, description, object_id, slug, is_active, created_at, updated_at, content_type_id, type_quiz_id) FROM stdin;
\.


--
-- Data for Name: requirements_courserequirement; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.requirements_courserequirement (id, "order", content, created_at, course_id) FROM stdin;
\.


--
-- Data for Name: videos_video; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.videos_video (id, url, duration_seconds, created_at, updated_at, lesson_id) FROM stdin;
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 108, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 7, true);


--
-- Name: courses_type_typecourse_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.courses_type_typecourse_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 3, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 27, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 50, true);


--
-- Name: highlights_coursehighlight_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.highlights_coursehighlight_id_seq', 1, false);


--
-- Name: learning_paths_learningpath_courses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.learning_paths_learningpath_courses_id_seq', 12, true);


--
-- Name: learning_paths_learningpath_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.learning_paths_learningpath_id_seq', 14, true);


--
-- Name: learning_paths_pathoutcome_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.learning_paths_pathoutcome_id_seq', 8, true);


--
-- Name: learning_paths_pathprerequisite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.learning_paths_pathprerequisite_id_seq', 3, true);


--
-- Name: learning_points_courselearningpoint_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.learning_points_courselearningpoint_id_seq', 1, false);


--
-- Name: lessons_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.lessons_lesson_id_seq', 16, true);


--
-- Name: modules_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.modules_module_id_seq', 5, true);


--
-- Name: outcomes_courseoutcome_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.outcomes_courseoutcome_id_seq', 1, false);


--
-- Name: question_types_typequestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.question_types_typequestion_id_seq', 1, false);


--
-- Name: quiz_answers_quizanswer_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_answers_quizanswer_id_seq', 1, false);


--
-- Name: quiz_attempts_quizattempt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_attempts_quizattempt_id_seq', 1, false);


--
-- Name: quiz_options_quizoption_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_options_quizoption_id_seq', 1, false);


--
-- Name: quiz_questions_question_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_questions_question_id_seq', 1, false);


--
-- Name: quiz_results_result_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_results_result_id_seq', 1, false);


--
-- Name: quiz_types_typequiz_allowed_question_types_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_types_typequiz_allowed_question_types_id_seq', 1, false);


--
-- Name: quiz_types_typequiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quiz_types_typequiz_id_seq', 1, false);


--
-- Name: quizzes_quiz_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.quizzes_quiz_id_seq', 1, false);


--
-- Name: requirements_courserequirement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.requirements_courserequirement_id_seq', 1, false);


--
-- Name: videos_video_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.videos_video_id_seq', 1, false);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: courses_course courses_course_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_pkey PRIMARY KEY (id);


--
-- Name: courses_course courses_course_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_slug_key UNIQUE (slug);


--
-- Name: courses_type_typecourse courses_type_typecourse_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_type_typecourse
    ADD CONSTRAINT courses_type_typecourse_name_key UNIQUE (name);


--
-- Name: courses_type_typecourse courses_type_typecourse_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_type_typecourse
    ADD CONSTRAINT courses_type_typecourse_pkey PRIMARY KEY (id);


--
-- Name: courses_type_typecourse courses_type_typecourse_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_type_typecourse
    ADD CONSTRAINT courses_type_typecourse_slug_key UNIQUE (slug);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: highlights_coursehighlight highlights_coursehighlight_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.highlights_coursehighlight
    ADD CONSTRAINT highlights_coursehighlight_pkey PRIMARY KEY (id);


--
-- Name: learning_paths_learningpath_courses learning_paths_learningp_learningpath_id_course_i_578ae3ce_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_learningpath_courses
    ADD CONSTRAINT learning_paths_learningp_learningpath_id_course_i_578ae3ce_uniq UNIQUE (learningpath_id, course_id);


--
-- Name: learning_paths_learningpath_courses learning_paths_learningpath_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_learningpath_courses
    ADD CONSTRAINT learning_paths_learningpath_courses_pkey PRIMARY KEY (id);


--
-- Name: learning_paths_learningpath learning_paths_learningpath_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_learningpath
    ADD CONSTRAINT learning_paths_learningpath_pkey PRIMARY KEY (id);


--
-- Name: learning_paths_learningpath learning_paths_learningpath_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_learningpath
    ADD CONSTRAINT learning_paths_learningpath_slug_key UNIQUE (slug);


--
-- Name: learning_paths_pathoutcome learning_paths_pathoutcome_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_pathoutcome
    ADD CONSTRAINT learning_paths_pathoutcome_pkey PRIMARY KEY (id);


--
-- Name: learning_paths_pathprerequisite learning_paths_pathprerequisite_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_pathprerequisite
    ADD CONSTRAINT learning_paths_pathprerequisite_pkey PRIMARY KEY (id);


--
-- Name: learning_points_courselearningpoint learning_points_courselearningpoint_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_points_courselearningpoint
    ADD CONSTRAINT learning_points_courselearningpoint_pkey PRIMARY KEY (id);


--
-- Name: lessons_lesson lessons_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons_lesson
    ADD CONSTRAINT lessons_lesson_pkey PRIMARY KEY (id);


--
-- Name: lessons_lesson lessons_lesson_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons_lesson
    ADD CONSTRAINT lessons_lesson_slug_key UNIQUE (slug);


--
-- Name: modules_module modules_module_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules_module
    ADD CONSTRAINT modules_module_pkey PRIMARY KEY (id);


--
-- Name: modules_module modules_module_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules_module
    ADD CONSTRAINT modules_module_slug_key UNIQUE (slug);


--
-- Name: outcomes_courseoutcome outcomes_courseoutcome_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outcomes_courseoutcome
    ADD CONSTRAINT outcomes_courseoutcome_pkey PRIMARY KEY (id);


--
-- Name: progress_courseprogress progress_courseprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_courseprogress
    ADD CONSTRAINT progress_courseprogress_pkey PRIMARY KEY (id);


--
-- Name: progress_courseprogress progress_courseprogress_user_id_course_id_63f5c6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_courseprogress
    ADD CONSTRAINT progress_courseprogress_user_id_course_id_63f5c6f7_uniq UNIQUE (user_id, course_id);


--
-- Name: question_types_typequestion question_types_typequestion_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_types_typequestion
    ADD CONSTRAINT question_types_typequestion_name_key UNIQUE (name);


--
-- Name: question_types_typequestion question_types_typequestion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_types_typequestion
    ADD CONSTRAINT question_types_typequestion_pkey PRIMARY KEY (id);


--
-- Name: question_types_typequestion question_types_typequestion_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.question_types_typequestion
    ADD CONSTRAINT question_types_typequestion_slug_key UNIQUE (slug);


--
-- Name: quiz_answers_quizanswer quiz_answers_quizanswer_attempt_id_question_id_aa54e245_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_answers_quizanswer
    ADD CONSTRAINT quiz_answers_quizanswer_attempt_id_question_id_aa54e245_uniq UNIQUE (attempt_id, question_id);


--
-- Name: quiz_answers_quizanswer quiz_answers_quizanswer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_answers_quizanswer
    ADD CONSTRAINT quiz_answers_quizanswer_pkey PRIMARY KEY (id);


--
-- Name: quiz_attempts_quizattempt quiz_attempts_quizattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts_quizattempt
    ADD CONSTRAINT quiz_attempts_quizattempt_pkey PRIMARY KEY (id);


--
-- Name: quiz_options_quizoption quiz_options_quizoption_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_options_quizoption
    ADD CONSTRAINT quiz_options_quizoption_pkey PRIMARY KEY (id);


--
-- Name: quiz_questions_question quiz_questions_question_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions_question
    ADD CONSTRAINT quiz_questions_question_pkey PRIMARY KEY (id);


--
-- Name: quiz_questions_question quiz_questions_question_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions_question
    ADD CONSTRAINT quiz_questions_question_slug_key UNIQUE (slug);


--
-- Name: quiz_results_result quiz_results_result_answer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_results_result
    ADD CONSTRAINT quiz_results_result_answer_id_key UNIQUE (answer_id);


--
-- Name: quiz_results_result quiz_results_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_results_result
    ADD CONSTRAINT quiz_results_result_pkey PRIMARY KEY (id);


--
-- Name: quiz_types_typequiz_allowed_question_types quiz_types_typequiz_allo_typequiz_id_typequestion_0f95c55d_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz_allowed_question_types
    ADD CONSTRAINT quiz_types_typequiz_allo_typequiz_id_typequestion_0f95c55d_uniq UNIQUE (typequiz_id, typequestion_id);


--
-- Name: quiz_types_typequiz_allowed_question_types quiz_types_typequiz_allowed_question_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz_allowed_question_types
    ADD CONSTRAINT quiz_types_typequiz_allowed_question_types_pkey PRIMARY KEY (id);


--
-- Name: quiz_types_typequiz quiz_types_typequiz_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz
    ADD CONSTRAINT quiz_types_typequiz_name_key UNIQUE (name);


--
-- Name: quiz_types_typequiz quiz_types_typequiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz
    ADD CONSTRAINT quiz_types_typequiz_pkey PRIMARY KEY (id);


--
-- Name: quiz_types_typequiz quiz_types_typequiz_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz
    ADD CONSTRAINT quiz_types_typequiz_slug_key UNIQUE (slug);


--
-- Name: quizzes_quiz quizzes_quiz_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_pkey PRIMARY KEY (id);


--
-- Name: quizzes_quiz quizzes_quiz_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_slug_key UNIQUE (slug);


--
-- Name: requirements_courserequirement requirements_courserequirement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirements_courserequirement
    ADD CONSTRAINT requirements_courserequirement_pkey PRIMARY KEY (id);


--
-- Name: videos_video videos_video_lesson_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_video
    ADD CONSTRAINT videos_video_lesson_id_key UNIQUE (lesson_id);


--
-- Name: videos_video videos_video_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_video
    ADD CONSTRAINT videos_video_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: courses_course_slug_9c670f14_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_course_slug_9c670f14_like ON public.courses_course USING btree (slug varchar_pattern_ops);


--
-- Name: courses_course_type_id_a7bfde75; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_course_type_id_a7bfde75 ON public.courses_course USING btree (type_id);


--
-- Name: courses_type_typecourse_name_4bea06e2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_type_typecourse_name_4bea06e2_like ON public.courses_type_typecourse USING btree (name varchar_pattern_ops);


--
-- Name: courses_type_typecourse_slug_546dacb3_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX courses_type_typecourse_slug_546dacb3_like ON public.courses_type_typecourse USING btree (slug varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: highlights_coursehighlight_course_id_605c013d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX highlights_coursehighlight_course_id_605c013d ON public.highlights_coursehighlight USING btree (course_id);


--
-- Name: learning_paths_learningpath_courses_course_id_ab08bfa9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX learning_paths_learningpath_courses_course_id_ab08bfa9 ON public.learning_paths_learningpath_courses USING btree (course_id);


--
-- Name: learning_paths_learningpath_courses_learningpath_id_79ca4b88; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX learning_paths_learningpath_courses_learningpath_id_79ca4b88 ON public.learning_paths_learningpath_courses USING btree (learningpath_id);


--
-- Name: learning_paths_learningpath_slug_65285068_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX learning_paths_learningpath_slug_65285068_like ON public.learning_paths_learningpath USING btree (slug varchar_pattern_ops);


--
-- Name: learning_paths_pathoutcome_path_id_c719a5cc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX learning_paths_pathoutcome_path_id_c719a5cc ON public.learning_paths_pathoutcome USING btree (path_id);


--
-- Name: learning_paths_pathprerequisite_path_id_332efd29; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX learning_paths_pathprerequisite_path_id_332efd29 ON public.learning_paths_pathprerequisite USING btree (path_id);


--
-- Name: learning_points_courselearningpoint_course_id_6049346c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX learning_points_courselearningpoint_course_id_6049346c ON public.learning_points_courselearningpoint USING btree (course_id);


--
-- Name: lessons_lesson_module_id_43312367; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX lessons_lesson_module_id_43312367 ON public.lessons_lesson USING btree (module_id);


--
-- Name: lessons_lesson_slug_af9ce118_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX lessons_lesson_slug_af9ce118_like ON public.lessons_lesson USING btree (slug varchar_pattern_ops);


--
-- Name: modules_module_course_id_df309efc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX modules_module_course_id_df309efc ON public.modules_module USING btree (course_id);


--
-- Name: modules_module_slug_9c6b9709_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX modules_module_slug_9c6b9709_like ON public.modules_module USING btree (slug varchar_pattern_ops);


--
-- Name: outcomes_courseoutcome_course_id_a5356d7a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX outcomes_courseoutcome_course_id_a5356d7a ON public.outcomes_courseoutcome USING btree (course_id);


--
-- Name: progress_courseprogress_course_id_e99f60f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX progress_courseprogress_course_id_e99f60f8 ON public.progress_courseprogress USING btree (course_id);


--
-- Name: question_types_typequestion_name_3797a28a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX question_types_typequestion_name_3797a28a_like ON public.question_types_typequestion USING btree (name varchar_pattern_ops);


--
-- Name: question_types_typequestion_slug_a91f9e56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX question_types_typequestion_slug_a91f9e56_like ON public.question_types_typequestion USING btree (slug varchar_pattern_ops);


--
-- Name: quiz_answers_quizanswer_attempt_id_e00d0591; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_answers_quizanswer_attempt_id_e00d0591 ON public.quiz_answers_quizanswer USING btree (attempt_id);


--
-- Name: quiz_answers_quizanswer_option_id_b2a7bc38; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_answers_quizanswer_option_id_b2a7bc38 ON public.quiz_answers_quizanswer USING btree (option_id);


--
-- Name: quiz_answers_quizanswer_question_id_bd36807d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_answers_quizanswer_question_id_bd36807d ON public.quiz_answers_quizanswer USING btree (question_id);


--
-- Name: quiz_attempts_quizattempt_quiz_id_ffab8873; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_attempts_quizattempt_quiz_id_ffab8873 ON public.quiz_attempts_quizattempt USING btree (quiz_id);


--
-- Name: quiz_options_quizoption_question_id_a6c7a184; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_options_quizoption_question_id_a6c7a184 ON public.quiz_options_quizoption USING btree (question_id);


--
-- Name: quiz_questions_question_quiz_id_a106235a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_questions_question_quiz_id_a106235a ON public.quiz_questions_question USING btree (quiz_id);


--
-- Name: quiz_questions_question_slug_6a1c2c03_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_questions_question_slug_6a1c2c03_like ON public.quiz_questions_question USING btree (slug varchar_pattern_ops);


--
-- Name: quiz_questions_question_type_question_id_c1fd6e79; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_questions_question_type_question_id_c1fd6e79 ON public.quiz_questions_question USING btree (type_question_id);


--
-- Name: quiz_types_typequiz_allowe_typequestion_id_d8082900; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_types_typequiz_allowe_typequestion_id_d8082900 ON public.quiz_types_typequiz_allowed_question_types USING btree (typequestion_id);


--
-- Name: quiz_types_typequiz_allowed_question_types_typequiz_id_21e7f113; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_types_typequiz_allowed_question_types_typequiz_id_21e7f113 ON public.quiz_types_typequiz_allowed_question_types USING btree (typequiz_id);


--
-- Name: quiz_types_typequiz_name_11fdb3ea_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_types_typequiz_name_11fdb3ea_like ON public.quiz_types_typequiz USING btree (name varchar_pattern_ops);


--
-- Name: quiz_types_typequiz_slug_36fed0e2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quiz_types_typequiz_slug_36fed0e2_like ON public.quiz_types_typequiz USING btree (slug varchar_pattern_ops);


--
-- Name: quizzes_quiz_content_type_id_221ab04c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quizzes_quiz_content_type_id_221ab04c ON public.quizzes_quiz USING btree (content_type_id);


--
-- Name: quizzes_quiz_slug_00008600_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quizzes_quiz_slug_00008600_like ON public.quizzes_quiz USING btree (slug varchar_pattern_ops);


--
-- Name: quizzes_quiz_type_quiz_id_c2eaaf8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX quizzes_quiz_type_quiz_id_c2eaaf8b ON public.quizzes_quiz USING btree (type_quiz_id);


--
-- Name: requirements_courserequirement_course_id_5ff132d6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX requirements_courserequirement_course_id_5ff132d6 ON public.requirements_courserequirement USING btree (course_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_course courses_course_type_id_a7bfde75_fk_courses_type_typecourse_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_type_id_a7bfde75_fk_courses_type_typecourse_id FOREIGN KEY (type_id) REFERENCES public.courses_type_typecourse(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: highlights_coursehighlight highlights_coursehig_course_id_605c013d_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.highlights_coursehighlight
    ADD CONSTRAINT highlights_coursehig_course_id_605c013d_fk_courses_c FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: learning_paths_learningpath_courses learning_paths_learn_course_id_ab08bfa9_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_learningpath_courses
    ADD CONSTRAINT learning_paths_learn_course_id_ab08bfa9_fk_courses_c FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: learning_paths_learningpath_courses learning_paths_learn_learningpath_id_79ca4b88_fk_learning_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_learningpath_courses
    ADD CONSTRAINT learning_paths_learn_learningpath_id_79ca4b88_fk_learning_ FOREIGN KEY (learningpath_id) REFERENCES public.learning_paths_learningpath(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: learning_paths_pathoutcome learning_paths_patho_path_id_c719a5cc_fk_learning_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_pathoutcome
    ADD CONSTRAINT learning_paths_patho_path_id_c719a5cc_fk_learning_ FOREIGN KEY (path_id) REFERENCES public.learning_paths_learningpath(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: learning_paths_pathprerequisite learning_paths_pathp_path_id_332efd29_fk_learning_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_paths_pathprerequisite
    ADD CONSTRAINT learning_paths_pathp_path_id_332efd29_fk_learning_ FOREIGN KEY (path_id) REFERENCES public.learning_paths_learningpath(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: learning_points_courselearningpoint learning_points_cour_course_id_6049346c_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_points_courselearningpoint
    ADD CONSTRAINT learning_points_cour_course_id_6049346c_fk_courses_c FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: lessons_lesson lessons_lesson_module_id_43312367_fk_modules_module_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lessons_lesson
    ADD CONSTRAINT lessons_lesson_module_id_43312367_fk_modules_module_id FOREIGN KEY (module_id) REFERENCES public.modules_module(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: modules_module modules_module_course_id_df309efc_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.modules_module
    ADD CONSTRAINT modules_module_course_id_df309efc_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: outcomes_courseoutcome outcomes_courseoutcome_course_id_a5356d7a_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.outcomes_courseoutcome
    ADD CONSTRAINT outcomes_courseoutcome_course_id_a5356d7a_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: progress_courseprogress progress_courseprogress_course_id_e99f60f8_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.progress_courseprogress
    ADD CONSTRAINT progress_courseprogress_course_id_e99f60f8_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_answers_quizanswer quiz_answers_quizans_attempt_id_e00d0591_fk_quiz_atte; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_answers_quizanswer
    ADD CONSTRAINT quiz_answers_quizans_attempt_id_e00d0591_fk_quiz_atte FOREIGN KEY (attempt_id) REFERENCES public.quiz_attempts_quizattempt(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_answers_quizanswer quiz_answers_quizans_option_id_b2a7bc38_fk_quiz_opti; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_answers_quizanswer
    ADD CONSTRAINT quiz_answers_quizans_option_id_b2a7bc38_fk_quiz_opti FOREIGN KEY (option_id) REFERENCES public.quiz_options_quizoption(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_answers_quizanswer quiz_answers_quizans_question_id_bd36807d_fk_quiz_ques; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_answers_quizanswer
    ADD CONSTRAINT quiz_answers_quizans_question_id_bd36807d_fk_quiz_ques FOREIGN KEY (question_id) REFERENCES public.quiz_questions_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_attempts_quizattempt quiz_attempts_quizattempt_quiz_id_ffab8873_fk_quizzes_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_attempts_quizattempt
    ADD CONSTRAINT quiz_attempts_quizattempt_quiz_id_ffab8873_fk_quizzes_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.quizzes_quiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_options_quizoption quiz_options_quizopt_question_id_a6c7a184_fk_quiz_ques; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_options_quizoption
    ADD CONSTRAINT quiz_options_quizopt_question_id_a6c7a184_fk_quiz_ques FOREIGN KEY (question_id) REFERENCES public.quiz_questions_question(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_questions_question quiz_questions_quest_type_question_id_c1fd6e79_fk_question_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions_question
    ADD CONSTRAINT quiz_questions_quest_type_question_id_c1fd6e79_fk_question_ FOREIGN KEY (type_question_id) REFERENCES public.question_types_typequestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_questions_question quiz_questions_question_quiz_id_a106235a_fk_quizzes_quiz_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_questions_question
    ADD CONSTRAINT quiz_questions_question_quiz_id_a106235a_fk_quizzes_quiz_id FOREIGN KEY (quiz_id) REFERENCES public.quizzes_quiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_results_result quiz_results_result_answer_id_d38f98d2_fk_quiz_answ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_results_result
    ADD CONSTRAINT quiz_results_result_answer_id_d38f98d2_fk_quiz_answ FOREIGN KEY (answer_id) REFERENCES public.quiz_answers_quizanswer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_types_typequiz_allowed_question_types quiz_types_typequiz__typequestion_id_d8082900_fk_question_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz_allowed_question_types
    ADD CONSTRAINT quiz_types_typequiz__typequestion_id_d8082900_fk_question_ FOREIGN KEY (typequestion_id) REFERENCES public.question_types_typequestion(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quiz_types_typequiz_allowed_question_types quiz_types_typequiz__typequiz_id_21e7f113_fk_quiz_type; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quiz_types_typequiz_allowed_question_types
    ADD CONSTRAINT quiz_types_typequiz__typequiz_id_21e7f113_fk_quiz_type FOREIGN KEY (typequiz_id) REFERENCES public.quiz_types_typequiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quizzes_quiz quizzes_quiz_content_type_id_221ab04c_fk_django_content_type_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_content_type_id_221ab04c_fk_django_content_type_id FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: quizzes_quiz quizzes_quiz_type_quiz_id_c2eaaf8b_fk_quiz_types_typequiz_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.quizzes_quiz
    ADD CONSTRAINT quizzes_quiz_type_quiz_id_c2eaaf8b_fk_quiz_types_typequiz_id FOREIGN KEY (type_quiz_id) REFERENCES public.quiz_types_typequiz(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: requirements_courserequirement requirements_courser_course_id_5ff132d6_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requirements_courserequirement
    ADD CONSTRAINT requirements_courser_course_id_5ff132d6_fk_courses_c FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: videos_video videos_video_lesson_id_0c59b394_fk_lessons_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.videos_video
    ADD CONSTRAINT videos_video_lesson_id_0c59b394_fk_lessons_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.lessons_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict W2OoopVba6Nd70qph6LJOj5zz2DltELpusW20MQLtK22Y9cHZyUlg9CLJRXwPI2

