# Generated by Django 5.2.16 on 2026-07-30 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du module')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description / Objectifs pédagogiques')),
                ('order', models.PositiveIntegerField(default=1, help_text='Position du module dans le cours (ex: 1, 2, 3...)', verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, help_text='Permet de masquer un module en cours de rédaction', verbose_name='Est publié')),
                ('is_free', models.BooleanField(default=False, help_text="Si vrai, l'ensemble des leçons du module est accessible gratuitement", verbose_name='Accès gratuit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='Cours associé')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course')],
            },
        ),
    ]
