# Generated by Django 5.2.16 on 2026-09-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_answers', '0001_initial'),
        ('quiz_attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz_attempts.quizattempt', verbose_name='quiz attempt'),
        ),
    ]
