# Generated by Django 5.2.16 on 2026-09-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_answers', '0002_initial'),
        ('quiz_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_in', to='quiz_options.quizoption', verbose_name='selected option'),
        ),
    ]
