# Generated by Django 5.2.16 on 2026-09-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='option text')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correct answer')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'quiz option',
                'verbose_name_plural': 'quiz options',
                'ordering': ['order'],
            },
        ),
    ]
